# Generated by Django 4.1.1 on 2022-10-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='send_date',
            new_name='date_created',
        ),
    ]
